FROM runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04

WORKDIR /apps

ENV DEBIAN_FRONTEND=noninteractive

# 更新源并安装编译依赖
RUN apt update && \
    apt install -y --no-install-recommends \
        build-essential \
        software-properties-common \
        libssl-dev \
        zlib1g-dev \
        libncurses5-dev \
        libncursesw5-dev \
        libreadline-dev \
        libsqlite3-dev \
        liblzma-dev \
        ffmpeg \
        libgl1  \
        libglib2.0-0 \
        cuda-toolkit-11-8 \
        wget \
        curl \
        llvm \
        libgdbm-dev \
        ca-certificates \
        libbz2-dev \
        libffi-dev \
        gnupg \
        git && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*　


# 添加 NVIDIA 包仓库和 GPG 密钥
RUN curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey  | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit.gpg && \
    . /etc/os-release && \
    echo "deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/amd64  $VERSION_CODENAME main" | tee /etc/apt/sources.list.d/nvidia-container-toolkit.list && \
    apt update && \
    apt install -y libnvidia-container-tools libnvidia-container1 \
    libcudnn8=8.9.7.29 && \
    rm -rf /var/lib/apt/lists/*

##编译安装 Python 3.8.20
RUN wget https://www.python.org/ftp/python/3.8.20/Python-3.8.20.tgz && tar xzf Python-3.8.20.tgz -C /
RUN cd  /Python-3.8.20 && \
    ./configure --enable-shared --with-ensurepip=install && \
    make -j$(nproc) && \
    make altinstall && \
    cd .. && \
    rm -rf Python-3.8.20*
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH

# 创建软链接以使用 python3.8 命令
RUN ln -s /usr/local/bin/python3.8 /usr/local/bin/python && \
    rm -f /usr/local/bin/pip && ln -s /usr/local/bin/pip3.8 /usr/local/bin/pip &&  pip install --upgrade pip



RUN git clone https://github.com/Holasyb918/HeyGem-Linux-Python-Hack
RUN mv HeyGem-Linux-Python-Hack /apps/HeyGem
#COPY HeyGem  /apps/HeyGem
#RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN cd /apps/HeyGem/ && echo "requests" >>  requirements_0.txt  && pip install -r requirements_0.txt --extra-index-url https://download.pytorch.org/whl/cu113 
RUN pip install runpod

COPY startup.sh / 
COPY rp_handler.py  / 
RUN chmod +x /startup.sh

CMD ["/startup.sh"]
